name: Maven CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'Siri'
        required: false
        type: string
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}
